### ISSUE TITLE
FDA API for food recall info will run without errors but Exception will occur

### ISSUE THREAD

**Issue by lukejavier** [WSU-4110/SafeFoodie#83]
Code has no errors but when the program is run, an exception is thrown stating that "a value of type 'Null' can't be assigned to a parameter of type 'String'", even though I see the nested values for reason_for_recall when I open the FDA's JSON file.

**Comment by savvyp** [comment]
Decided to make this a manual button for the user to click. It will display if there were any recalls without an API calling the notif
